# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 07:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelldata',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), blank=True, null=True, size=None),
        ),
    ]
