# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=200, verbose_name='\u540d\u79f0')),
                ('url', models.URLField(blank=True, null=True, verbose_name='\u7f51\u7ad9')),
                ('flag', models.IntegerField(default=0)),
                ('brand_type', models.IntegerField(choices=[(0, '\u56fd\u724c'), (1, '\u65e5\u724c')], verbose_name='\u7c7b\u522b')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand_images', verbose_name='Logo')),
                ('isCopycat', models.BooleanField(default=False, verbose_name='\u5c71\u5be8')),
                ('abbr', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u7b80\u79f0')),
                ('weibo', models.URLField(blank=True, null=True, verbose_name='\u5fae\u535a')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
            ],
            options={
                'verbose_name': '\u54c1\u724c',
                'verbose_name_plural': '\u54c1\u724c',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
                ('rgb', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': '\u989c\u8272',
                'verbose_name_plural': '\u989c\u8272',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '\u7279\u70b9',
                'verbose_name_plural': '\u7279\u70b9',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
    ]
