# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-06 22:40
from __future__ import unicode_literals
import os

from django.db import migrations, models

from dress.migration_utils import import_csv, reverse_csv

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

color_csv_file = os.path.join(BASE_DIR, '0002_auto_20180307_0640.color.csv')
feature_csv_file = os.path.join(BASE_DIR, '0002_auto_20180307_0640.feature.csv')

def forwards(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    # Your migration code goes here
    import_csv(apps, color_csv_file, 'Color')
    import_csv(apps, feature_csv_file, 'Feature')



def reverse(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    # Your migration code goes here
    reverse_csv(apps, color_csv_file, 'Color')
    reverse_csv(apps, feature_csv_file, 'Feature')

class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='attr_type',
            field=models.IntegerField(choices=[(0, 'not show'), (1, 'show')], default=0),
        ),
        migrations.AddField(
            model_name='color',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True, db_index=True),
        ),
        migrations.AddField(
            model_name='color',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='attr_type',
            field=models.IntegerField(choices=[(0, 'not show'), (1, 'show')], default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True, db_index=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='attr_type',
            field=models.IntegerField(choices=[(0, 'not show'), (1, 'show')], default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True, db_index=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(forwards, reverse),
    ]
