# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0002_auto_20180307_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': '版型', 'verbose_name_plural': '版型'},
        ),
        migrations.AddField(
            model_name='brand',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='external_src',
            field=models.IntegerField(blank=True, choices=[(1, 'lolibrary')], null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='external_src',
            field=models.IntegerField(blank=True, choices=[(1, 'lolibrary')], null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='external_src',
            field=models.IntegerField(blank=True, choices=[(1, 'lolibrary')], null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='external_src',
            field=models.IntegerField(blank=True, choices=[(1, 'lolibrary')], null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='flag',
            field=models.IntegerField(choices=[(10, 'lolib')], default=0),
        ),
        migrations.AlterField(
            model_name='color',
            name='attr_type',
            field=models.IntegerField(choices=[(0, 'lolib basic'), (1, 'lolib extended'), (2, 'lolib new')], default=0),
        ),
        migrations.AlterField(
            model_name='feature',
            name='attr_type',
            field=models.IntegerField(choices=[(0, 'lolib basic'), (1, 'lolib extended'), (2, 'lolib new')], default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='attr_type',
            field=models.IntegerField(choices=[(0, 'lolib basic'), (1, 'lolib extended'), (2, 'lolib new')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set([('external_id', 'external_src')]),
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together=set([('external_src', 'external_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([('external_src', 'external_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('external_src', 'external_id')]),
        ),
    ]
